### ISSUE TITLE
Add User Signup/Login

### ISSUE THREAD

**Issue by aramisf** [FForstbach/great-city#5]
That one looks pretty obvious, right? 😝 
The important thing to notice is that this issue has some priority on others, since functionalities like commenting require the user to be logged in.

**Comment by FForstbach** [comment]
@aramisf we could leave this and the commenting out on the very first version. and then implement USER plus features on next iteration.

**Comment by aramisf** [comment]
Ok. Sorry, I haven't seen your message before.
Let do that way :+1:
